# Generated by Django 5.1.6 on 2025-03-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='image',
            field=models.ImageField(upload_to='house/'),
        ),
    ]
