# Generated by Django 5.1.7 on 2025-03-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='etat',
            field=models.CharField(choices=[('disponible', 'disponible'), ('reservée', 'reservée'), ('occupee', 'occupee')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
