# Generated by Django 5.1.7 on 2025-03-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_logement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logement',
            old_name='category',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='logement',
            old_name='price',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='logement',
            old_name='neighborhood',
            new_name='quartier',
        ),
        migrations.RenameField(
            model_name='logement',
            old_name='area',
            new_name='superficie',
        ),
        migrations.RenameField(
            model_name='logement',
            old_name='city',
            new_name='ville',
        ),
    ]
