# Generated by Django 5.1.7 on 2025-03-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_rename_category_logement_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
